# Site settings
title: "Allen Kleiner"
email: "akleiner24@gmail.com"
description: "Allen Kleiner is a software developer currently studying Comptuter Science at the University of Illinois at Urbana-Champaign"
baseurl: ""
url: "http://allenk.me"
title_description: "Hi there! My name is Allen Kleiner, and I am currently a third-year computer science student at UIUC. I've previously worked at Apple, Wolfram Research, and State Farm. My interests are full-stack web development, information retreival, systems programming, and application performance."
title_image: "https://scontent-sjc2-1.xx.fbcdn.net/hphotos-xpf1/v/t1.0-9/10614265_10205087553093730_6837536050064290726_n.jpg?oh=c6b8e4efdf6ba1cd34eeab7418312787&oe=56805C57"
google_analytics: "UA-20365477-4"
disqus_account: cartenoire
github_repository: https://github.com/akleiner2/akleiner2.github.io.git
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: ak34_
github_username:  akleiner2
linkedin_link: http://linkedin.com/in/allenkleiner

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]
